flight_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('JDBC_HOST') }}"
      port: "{{ env_var('JDBC_PORT') | int }}"
      user: "{{ env_var('POSTGRESQL_USER') }}"
      password: "{{ env_var('POSTGRESQL_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRESQL_DATABASE') }}"
      schema: public
      threads: 4
